"""fix_muscle_group_to_string

Revision ID: 957fe72dfc47
Revises: 6b0b050650c8
Create Date: 2026-06-02 06:54:08.685997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957fe72dfc47'
down_revision: Union[str, Sequence[str], None] = '6b0b050650c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'muscle_group',
               existing_type=postgresql.ENUM('CHEST', 'BACK', 'LEGS', 'SHOULDERS', 'ARMS', 'CORE', 'FULL_BODY', 'CARDIO', name='muscle_group'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'muscle_group',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CHEST', 'BACK', 'LEGS', 'SHOULDERS', 'ARMS', 'CORE', 'FULL_BODY', 'CARDIO', name='muscle_group'),
               existing_nullable=False)
    # ### end Alembic commands ###
